### ISSUE TITLE
Music - Artist & Album titles doubling up

### ISSUE THREAD

**Issue by Kanector** [ivarbrandt/skin.nimbus#117]
In the music menu, the artist and title are showing twice on top of each other. In album view there also isn't any artwork. Both are working fine in Fentastic and Estuary.

![duplicate-titles](https://github.com/user-attachments/assets/8ebc986b-91a1-4987-af77-6b21e178c366)

**Comment by ivarbrandt** [comment]
I don't know anything bout music in this skin. I've never utilized it.

That being said, I'll take a look at the titles doubling up.

**Comment by Kanector** [comment]
That's great thanks. For the artwork in album view it would be great if it was just the same as Estuary and what you did in Fentastic. At the moment it's in the new list viewtype, but that doesn't show any album artwork. The left side menu also doesn't seem to work.

**Comment by ivarbrandt** [comment]
You're not understanding. Not having music on my Kodi limits what I can fix for music-related features/functionality.

I think I fixed the labels doubling up for the widgets. You'll have to test it out.

As for the other views, I can't work on those because like I said I don't have any music on my Kodi.

**Comment by Kanector** [comment]
That's great, thanks.
