### ISSUE TITLE
Nimbus helper error (no ratings displayed)

### ISSUE THREAD

**Issue by homeslixe** [ivarbrandt/skin.nimbus#128]
TVos version of Kodi 21.1. Nimbus and Nimbus Helper are current.

Nimbus Helper error consistently prompts and unable to view ratings on any view on both widgets and in libraries. Multiple mdblist API's tried. API's are good and ratings settings load in Ratings Management. I suspect the two issues may be related. I've tried, unsuccessfully, to resolve with multiple reinstalls of Nimbus and Kodi.

I'm unable to edit scripts to test further as not installed on PC. 

Any help you can offer would be greatly appreciated!

Log: https://paste.kodi.tv/oyebufupow

**Comment by ivarbrandt** [comment]
Unfortunately, Nimbus isn't supported on tvOS. The core issue is that tvOS isn't officially supported by Kodi, and its locked-down nature prevents certain required components from working. Specifically, the error you're seeing occurs because Nimbus uses PIL for image processing functions (blur effects), but PIL's binaries aren't properly signed for tvOS and therefore can't be loaded.
