### ISSUE TITLE
Clear logo doesn't appear on some landscape poster

### ISSUE THREAD

**Issue by Mollver** [ivarbrandt/skin.nimbus#33]
Hi, I'm using POV addon with Nbus skin, and I noticed that some titles posters are not have clear logo on them, while at other skins they appeared.

Wish you understand my problem and can fix it.

**Comment by ivarbrandt** [comment]
There's a good chance this isn't skin related. Please provide some examples I can look at with Nimbus vs the other skin you say showed it.

**Comment by Mollver** [comment]
![20240803_031731](https://github.com/user-attachments/assets/a341c6a7-de4d-4dd5-a27e-89c9e56bb420)
Here are images for landscape widget from Nimbus VS Arctic Fuse skin 
![Uploading 20240803_031723.jpg…]()

**Comment by Mollver** [comment]
![Uploading 20240803_031527.jpg…]()
![Uploading 20240803_031723.jpg…]()
![Uploading 20240803_031512.jpg…]()

**Comment by ivarbrandt** [comment]
I can't see any of those images. Add one image at a time to the comment, wait for it to finish, then add the next.

**Comment by Mollver** [comment]
![20240803_031527](https://github.com/user-attachments/assets/fd6d8f6c-4eab-4e8e-a3ba-0e6be13ecd1b)

Oh I'm sorry here them again

**Comment by Mollver** [comment]
![20240803_031723](https://github.com/user-attachments/assets/a668219e-f8c0-49f0-9449-d3283ffaa633)
.

**Comment by Mollver** [comment]
![20240803_031512](https://github.com/user-attachments/assets/758966af-8c3f-43b9-960c-4133d06a537c)
.

**Comment by Mollver** [comment]
As you see .. Bad boys, deadsea and Myspy clearlogo are shown on arctic fuse while they not on Nimbus

**Comment by ivarbrandt** [comment]
Thank you for re-uploading those.

Clearlogo isn't available on landscape widgets in Nimbus. Your options are landscape:
![Screenshot_20240803-141846](https://github.com/user-attachments/assets/5dcb55d5-6f5d-4da7-abf5-e24d6777018f)

or fanart:
![Screenshot_20240803-141910](https://github.com/user-attachments/assets/4eebd196-a8e8-42f3-abc6-d35c21f5bd3d)

You can find clearlogo in the fanart in the default list view:
![Screenshot_20240803-142414](https://github.com/user-attachments/assets/ffbef93d-26bc-4dd9-a07a-5c69e3a9a59f)

**Comment by Mollver** [comment]
Im sorry, I still not get it, why some titles have clearlogo on it but other not.
I select landscape mode.
As pictures you upload you can find badboys have have clearlogo on its landscape widget.

**Comment by ivarbrandt** [comment]
Landscape and clearlogo are two different types of art. In Nimbus widgets, you aren't seeing clearlogo when you choose landscape. I know the clearlogo has the same style as the logo in landscape art, but they are not the same.

If you see fanart instead of landscape in Nimbus, its either because you have fanart instead of landscape enabled, or landscape art isnt available for that title.

Also, make sure you have the landscape widgets set to default in the artwork settings on the home screen.

I recommend watching the first 2 or 3 minutes of this video to learn how to use the different artwork settings: https://rb.gy/l9zpkl
