### ISSUE TITLE
Quality Thubnails

### ISSUE THREAD

**Issue by xavengedx** [ivarbrandt/skin.nimbus#43]
With POV the quality of the fanarts and clearlogo and poster was incredible after configuring, it was a little slower but I don't mind, I hope that one day you can add the movie collection function to POV too! Thanks for always helping.

![screenshot00006](https://github.com/user-attachments/assets/fa79c323-ba1f-47bd-86e2-35965e2abd00)
![screenshot00005](https://github.com/user-attachments/assets/04cd9dce-4eb9-479b-91d8-efab301d8201)
![screenshot00004](https://github.com/user-attachments/assets/7575ed3b-4886-455f-bc12-ecc8c64c13c8)

**Comment by ivarbrandt** [comment]
Looking cleannn. The collection function comes from Fen Light and the skin uses it. So the dev of POV would have to implement something like it, or maybe later I can integrate it directly into Nimbus.

**Comment by hcgiub001** [comment]
The Colection function makes most sense if you have it open to movie set if a movie belongs to a collection (this is a Fenlight feature). You can ask POV dev @kodifitzwell to have this function and also have a listitem for such movies so skinners could make use of it

**Comment by xavengedx** [comment]
The pov extras tab is the same as fen light and on the extra page when a film belongs to a film collection, at the end of the extra page it shows the film collection. I thought it was from this same place that you could get this information and put it on the home page

![screenshot00007](https://github.com/user-attachments/assets/92da354a-3686-47ca-9fff-48fb2fa599c4)

**Comment by hcgiub001** [comment]
from ivarbrandt "We still won't know whether or not a movie is part of a set until we get to the context menu. This could be fixed by setting a property for all movie items and then I can use that to display a small image that tells you it belongs to a set"

This was asked by to the Dev of Fenlight, which he granted the request, so Nimbus could use that trigger to show the icon.

I'm not sure what ivarbrandt meant when he said "or maybe later I can integrate it directly into Nimbus", is ivarbrandt able to do it without having to ask POV dev to add this?

You could ask at POV github 
https://github.com/kodifitzwell/repo

also if you have it open the collection on select, that is a Fenlight feature, POV would also have to add this feature, you could ask him if he'll consider adding it along with the tag.

**Comment by ivarbrandt** [comment]
> I'm not sure what ivarbrandt meant when he said "or maybe later I can integrate it directly into Nimbus", is ivarbrandt able to do it without having to ask POV dev to add this?

I can most likely integrate the collection icon feature into Nimbus. However I don't see the point if the addon being used doesn't have access to the collection.

**Comment by hcgiub001** [comment]
> > I'm not sure what ivarbrandt meant when he said "or maybe later I can integrate it directly into Nimbus", is ivarbrandt able to do it without having to ask POV dev to add this?
> 
> I can most likely integrate the collection icon feature into Nimbus. However I don't see the point if the addon being used doesn't have access to the collection.

kodifitzwell is a great dev and actively developing POV, he'll easily add this feature so we can access collections from context menu, at which point we can ask kodifitzwell to have a listitem to? since @xavengedx is interested in this feature in POV, i'll leave it in his hand.
Also Umbrella which is another popular addon has access to collections
![Screenshot (310)](https://github.com/user-attachments/assets/49ae19c3-6b98-4098-be79-53cbd7c76d26)
"browse collection"

if 3 of the most used addons has access to collections then others will follow suit since it's a popular feature, then Nimbus collection icon has massive value, and only skin that has this

**Comment by xavengedx** [comment]
> collection

Of course, with the ability to open the film and open a page with the collection, it's incredible! But if you activate it even though the Addon doesn't have this feature, it will also be very good! Because there are films that I don't even imagine have a collection, and I leave it configured in POV so that when I open a film or series, they both open on the POV extras screen, which is the same as Fen light, and on the POV extras page I find the collection! Even if the POV developer fails to bring this feature, if you just add the icon it will be of great value! 🚀

**Comment by xavengedx** [comment]
Of course, with the ability to open the film and open a page with the collection, it's incredible! But if you activate it even though the Addon doesn't have this feature, it will also be very good! Because there are films that I don't even imagine have a collection, and I leave it configured in POV so that when I open a film or series, they both open on the POV extras screen, which is the same as Fen light, and on the POV extras page I find the collection! Even if the POV developer fails to bring this feature, if you just add the icon it will be of great value! 🚀

**Comment by hcgiub001** [comment]
> Of course, with the ability to open the film and open a page with the collection, it's incredible! But if you activate it even though the Addon doesn't have this feature, it will also be very good! Because there are films that I don't even imagine have a collection, and I leave it configured in POV so that when I open a film or series, they both open on the POV extras screen, which is the same as Fen light, and on the POV extras page I find the collection! Even if the POV developer fails to bring this feature, if you just add the icon it will be of great value! 🚀

create an feature request from POV here
https://github.com/kodifitzwell/repo

just ask him Fenlight has a feature you like and was wondering if he can add it, explain what the feature is.
let him know Nimbus is willing to add an icon for movies that belong to a collection but Nimbus dev said "We still won't know whether or not a movie is part of a set until we get to the context menu. This could be fixed by setting a property for all movie items and then I can use that to display a small image that tells you it belongs to a set"
and if he can add this like Fenlight  has.

I'm not sure how Dev's feel about their code being used, the dev of POV could easily see how Tikipeter did it and use the same code with some modifications. either way he's a good dev and can think of his own solution too. 

so yeah make an issue with POV dev and ask him. I gave you the link.

I think opening up collection if a movie is part of a collection should be default. mainly because it's virtually instant load, so we don't really lose anything. I might ask Tikipeter for this later. right now I think I've asked him 3 feature request LMAO
I'm a serial feature requester, you can ask @ivarbrandt

**Comment by ivarbrandt** [comment]
The collection icon is now built into Nimbus. I also added whether or not a movie is the first one in the collection. Update is now available.

**Comment by xavengedx** [comment]
you are the best, thank you for taking your time and bringing a skin with many features ahead of any other skin! Looking forward to getting home to test the new functions! Thank you @ivarbrandt

**Comment by hcgiub001** [comment]
background blur is sweeter. @ivarbrandt for what it's worth, I much preferred the older logo for collections, this one looks like a Pokémon ball and the writing is way to small to notice what it says and I liked the colour change in the logo before whereas this one doesn't, would you consider changing it back?

I'm not sure where the ability to see if it's first in the collection is. I checked in shows and you have a leaf and seems like a sun logo?
is the leaf meant to be it's the first in the collection? in the movies their is no distinction.

I checked in POV and can't see the collections icon for movies either.

**Comment by ivarbrandt** [comment]
Sounds like you're not on the latest version,` 0.1.19`. 

After you update, go check the changelog in Skin settings > Extras. It will tell you everything you need to know about the changes made and it'll check to make sure you have the latest version of the helper installed which is needed for the new features I mentioned.

**Comment by hcgiub001** [comment]
I'm using this repo
https://ivarbrandt.github.io/repository.ivarbrandt/
I went into Nimbus and don't have the option to update
![Screenshot (326)](https://github.com/user-attachments/assets/60763eb8-3684-4261-9a98-6a4aa4ff8154)
Maybe I need to wait?
I'm not familiar with updating addons so excuse my ignorance

**Comment by ivarbrandt** [comment]
Auto updating is not the way to go in Kodi. You always want to manually update. For a variety of reasons. 

Anyways, go into Settings, Addons, press left to get into the side menu. At the bottom, under Misc Options click Check for Updates. It likely to find my update right away and install it because you have Auto updates enabled. Go back to the home screen and wait for it to reload your widgets. Then follow the steps I outlined in my previous comment.

**Comment by hcgiub001** [comment]
I seriously don't know what to say. It's beyond gorgeous, it's beautiful! do you have background in art?
I think it's hands down the best looking skin. the extra information with the 1 in collections icon is awesome!
the colours are just wow and damn you included the blur into everything, you really meant it!

I really like the fade of elements so the trailer is highlighted! nice. one suggestion, not many people will read changelog, and I'm assuming most will press back button when they want to exit the trailer, so if you can have back button exit a trailer would be cool.
I really don't feel like watching a movie and just go explore the skin haha. really good job! I'm shocked how much you've improved, do you mind if I make a video of this in reddit?
thanks for this, love it.

**Comment by hcgiub001** [comment]
I'm impressed how you managed to integrate collections! can I ask what information can you access?

**Comment by ivarbrandt** [comment]
> do you have background in art?

Nah, I just like to build things and I have an eye for detail.

> the colours are just wow and damn you included the blur into everything

Yeah it might be overkill for some that's why it's optional. I personally love it. 

> I'm shocked how much you've improved, do you mind if I make a video of this in reddit?

This was one of the bigger updates for sure. I don't mind. You might wanna update it to `0.1.20` before you do as I just pushed a small bug fix.

> can I ask what information can you access?

Same place I get the ratings from, MDbList.

**Comment by xavengedx** [comment]
> The collection icon is now built into Nimbus. I also added whether or not a movie is the first one in the collection. Update is now available.

I just updated and checked the latest updates and they were incredible, without a doubt we are facing the best skin created for KODI, Congratulations man! Incredible.

I just have a bug in the trailer, when I press to go back once, it opens the trailer in full screen, then when I press to go back again it closes the trailer but closes KODI too.

But that's just a detail, thanks for adding the collection icon for all the addons, it looks really good!

**Comment by xavengedx** [comment]
**This is very BEAUTIFUL! Thank you very much**

![screenshot00009](https://github.com/user-attachments/assets/2d32b699-e01c-44ba-8ffb-a7d40902119d)
![screenshot00008](https://github.com/user-attachments/assets/af14d28d-5f0d-4f8b-9cc5-2ac64d67186f)
![screenshot00011](https://github.com/user-attachments/assets/a31ffc1f-6568-4b4f-bfd4-dbf13c782e93)
![screenshot00010](https://github.com/user-attachments/assets/34500869-94cf-421c-a4da-bf06f45148d5)
