### ISSUE TITLE
[BUG] Umbrella viewtypes

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#71]
for some reason I thought this was a design decision by umbrella but now comparing to estuary it seems nimbus isn't
showing them correctly

![Screenshot (404)](https://github.com/user-attachments/assets/fcd4758d-ad92-4893-a2b1-621d7bb0a7b5)

![Screenshot (405)](https://github.com/user-attachments/assets/e60a2c69-422d-446f-88e0-6c7cba8d37df)

![Screenshot (406)](https://github.com/user-attachments/assets/30fb25a2-e2c2-424e-886d-9def918c5016)

it's not bringing up the fanart either

side note. love the work you did on dramacool. it's better than having it on estuary, seems you specifically hand fixed each viewtype and you even made a title from the list items (removing sub etc) thanks

**Comment by ivarbrandt** [comment]
It's working fine for me..

![Screenshot_20240818-124336](https://github.com/user-attachments/assets/9d62ae3c-bf39-421a-aa95-edba8888b393)

**Comment by hcgiub001** [comment]
could be just my setup, here is
kodi log : https://paste.kodi.tv/xovapavuve

I made a video
https://streamable.com/hn9jpn

if nothing showing in logs, just close it since no one else has come forward

I'm not sure if it's important but
"2024-08-18 19:14:08.570 T:24548 warning <general>: Skin has invalid include: TVShowWidgets
2024-08-18 19:14:08.570 T:24548 warning <general>: Skin has invalid include: Custom1Widgets
2024-08-18 19:14:08.571 T:24548 warning <general>: Skin has invalid include: Custom2Widgets
2024-08-18 19:14:08.572 T:24548 warning <general>: Skin has invalid include: Custom3Widgets
2024-08-18 19:14:08.574 T:24548 warning <general>: Skin has invalid include: 
2024-08-18 19:14:08.585 T:24548    info <general>: Skipped 5 duplicate messages..
2024-08-18 19:14:08.585 T:24548 warning <general>: Skin has invalid include: TVShowsMainMenu
2024-08-18 19:14:08.585 T:24548 warning <general>: Skin has invalid include: Custom1MainMenu
2024-08-18 19:14:08.585 T:24548 warning <general>: Skin has invalid include: Custom2MainMenu
2024-08-18 19:14:08.585 T:24548 warning <general>: Skin has invalid include: Custom3MainMenu"

**Comment by ivarbrandt** [comment]
No idea. When I first downloaded Umbrella and clicked Now playing (TMDb), there was a little popup asking me if I wanted to install the metadata utils module. I clicked yes, and then everything worked fine. Maybe that's what you're missing.

> I'm not sure if it's important but

This might be happening because you are clicking buttons right after the skin updates, which isn't giving the skin a chance to remake the widgets. This is important even if you don't have any widgets. Next time the skin updates, after going to the home screen, wait for it kind of flash/blink. If you have widgets that's when you'll see the widgets loading again. If you don't it'll look like a small flash lol. Thats when you can use it normally again.

For now, click Remake menus and widgets in Skin settings. That should fix the issue.

**Comment by hcgiub001** [comment]
I'm pretty sure it's something with my setup, for now I'm closing and probably just do a fresh install. honestly I don't actually use Umbrella so It's not a big issue. thanks again
